import { jsPDF } from "jspdf";

export interface PrescriptionPdfData {
  doctorName: string;
  doctorSpecialty: string;
  patientName: string;
  patientEmail: string;
  date: string;
  time: string;
  diagnosis?: string;
  report?: string;
  medicines?: string;
}

const PAGE_WIDTH = 595.28; // A4 in pt
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function addSection(doc: jsPDF, y: number, label: string, value: string): number {
  if (y > PAGE_HEIGHT - 100) {
    doc.addPage();
    y = MARGIN;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 90);
  doc.text(label.toUpperCase(), MARGIN, y);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11.5);
  doc.setTextColor(20, 20, 20);
  const lines = doc.splitTextToSize(value || "—", CONTENT_WIDTH) as string[];
  for (const line of lines) {
    if (y > PAGE_HEIGHT - 60) {
      doc.addPage();
      y = MARGIN;
    }
    doc.text(line, MARGIN, y);
    y += 15;
  }
  return y + 14;
}

// Generates a formatted prescription PDF for a single completed visit and
// triggers a browser download. No server round-trip — everything happens client-side.
export function downloadPrescriptionPdf(data: PrescriptionPdfData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20, 110, 90);
  doc.text("Curo", MARGIN, y);
  doc.setFontSize(11);
  doc.setTextColor(110, 110, 110);
  doc.setFont("helvetica", "normal");
  doc.text("Consultation & Prescription Summary", MARGIN, y + 18);
  y += 44;

  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 26;

  // Doctor / patient / visit meta block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12.5);
  doc.setTextColor(20, 20, 20);
  doc.text(data.doctorName, MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(90, 90, 90);
  doc.text(data.doctorSpecialty, MARGIN, y + 14);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12.5);
  doc.setTextColor(20, 20, 20);
  doc.text(data.patientName, PAGE_WIDTH / 2, y, { align: "left" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(90, 90, 90);
  doc.text(data.patientEmail, PAGE_WIDTH / 2, y + 14);
  y += 34;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(90, 90, 90);
  doc.text(`Visit: ${data.date} at ${data.time}`, MARGIN, y);
  y += 24;

  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 28;

  // Body sections
  y = addSection(doc, y, "Diagnosis", data.diagnosis || "");
  y = addSection(doc, y, "Report / Notes", data.report || "");
  y = addSection(doc, y, "Medicines Prescribed", data.medicines || "");

  // Footer disclaimer
  if (y > PAGE_HEIGHT - 80) {
    doc.addPage();
    y = MARGIN;
  }
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, PAGE_HEIGHT - 60, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 60);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(140, 140, 140);
  doc.text(
    "This is a demo document generated by Curo and is not a legally valid prescription.",
    MARGIN,
    PAGE_HEIGHT - 42
  );

  const safePatient = data.patientName.replace(/\s+/g, "-").toLowerCase();
  doc.save(`prescription-${safePatient}-${data.date}.pdf`);
}