import doctorsData from "@/data/doctors.json";
import reviewsData from "@/data/reviews.json";
import specialtiesData from "@/data/specialties.json";
import { Doctor, Review, Specialty } from "./types";

export const doctors = doctorsData as Doctor[];
export const reviews = reviewsData as Review[];
export const specialties = specialtiesData as Specialty[];

export function getDoctorBySlug(slug: string): Doctor | undefined {
  return doctors.find((d) => d.slug === slug);
}

export function getReviewsForDoctor(doctorId: string): Review[] {
  return reviews.filter((r) => r.doctorId === doctorId);
}

export function cn(...classes: (string | false | undefined | null)[]) {
  return classes.filter(Boolean).join(" ");
}

// Turns a start time, end time, and per-patient duration into a list of
// 12-hour formatted slot labels, e.g. "10:00"–"11:00" at 20 min → 3 slots.
export function generateSlots(start: string, end: string, durationMinutes: number): string[] {
  if (!start || !end || !durationMinutes || durationMinutes <= 0) return [];
  const [sh, sm] = start.split(":").map(Number);
  const [eh, em] = end.split(":").map(Number);
  let cursor = sh * 60 + sm;
  const endMinutes = eh * 60 + em;
  const out: string[] = [];
  while (cursor + durationMinutes <= endMinutes) {
    const h24 = Math.floor(cursor / 60);
    const m = cursor % 60;
    const period = h24 >= 12 ? "PM" : "AM";
    const h12 = h24 % 12 === 0 ? 12 : h24 % 12;
    out.push(`${String(h12).padStart(2, "0")}:${String(m).padStart(2, "0")} ${period}`);
    cursor += durationMinutes;
  }
  return out;
}

// Builds a plain-text prescription and triggers a browser download. Client-side
// only — call this from an onClick handler, never during server rendering.
export function downloadPrescription(appointment: {
  doctorName: string;
  doctorSpecialty: string;
  patientName: string;
  date: string;
  time: string;
  diagnosis?: string;
  report?: string;
  medicines?: string;
}) {
  const lines = [
    "CURO — CONSULTATION SUMMARY",
    "----------------------------------------",
    `Patient: ${appointment.patientName}`,
    `Doctor: ${appointment.doctorName} (${appointment.doctorSpecialty})`,
    `Visit: ${appointment.date} at ${appointment.time}`,
    "----------------------------------------",
    "",
    `Diagnosis: ${appointment.diagnosis || "—"}`,
    "",
    `Notes: ${appointment.report || "—"}`,
    "",
    `Medicines prescribed: ${appointment.medicines || "—"}`,
    "",
    "----------------------------------------",
    "This is a demo document generated by Curo.",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `prescription-${appointment.doctorName.replace(/\s+/g, "-")}-${appointment.date}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}